### ISSUE TITLE
Test file does not accord ESLint configured style.

### ISSUE THREAD

**Issue by lucallero** [markpenovich/cryptocurrency-unit-convert#3]
I've noticed that tests.js file style differs from the one configured on the ESLint configuration file (.eslintrc.json.). This is a little weird, as index.js passes esLint verification and tests don't. 

Another little thing is that ESLint is configured to use double quotes. I wonder if is it possible to use single quotes and convert index.js to have same style tests.js,  what would result in only one style for the project.

If you agree I can help you with this tiny refactoring, a find/replace actually.

**Comment by markpenovich** [comment]
Yes let's change from double to single quotes for consistency.
