### ISSUE TITLE
BCH convesion

### ISSUE THREAD

**Issue by bookmoons** [markpenovich/cryptocurrency-unit-convert#5]
Is BCH conversion ready to use? I see it's in the docs but it doesn't seem to be included in the npm package.

```js
const Units = require('cryptocurrency-unit-convert')
Units.convertBCH('1000', 'satoshi', 'bch')
// TypeError: Units.convertBCH is not a function
```

Would really like to use it in my code. This seems like the cleanest package available.

**Comment by markpenovich** [comment]
Updated on NPM. Should be working now.

**Comment by bookmoons** [comment]
It's working really well. Thanks a lot.
